n = input('Digita alog: ')
print('O tipo primitivo desse valor é {}'.format(type(n)))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um numero ? {}'.format(n.isnumeric()))
print('É alfabético ? {}'.format(n.isalpha()))
print('É alfanumerico ? {}'.format(n.isalnum()))
print('Está em maiuscula ? {}'.format(n.isupper()))
print('Está em minusculo ? {}'.format(n.islower()))
print('Está capitalizada ? {}'.format(n.istitle()))
