import pygame
pygame.mixer.init()
pygame.mixer.music.load('teste.mp3')
pygame.mixer.music.play()
pygame.mixer.music.play()
pygame.mixer.music.play()
pygame.mixer.music.play()
pygame.mixer.music.play()
input()
pygame.event.wait()
pygame.mixer.close()